apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sendbird-chat-sdk-windows
  description: Chat SDK v3 for Windows
  annotations:
    github.com/project-slug: sendbird/SendBird-SDK-Windows
spec:
  type: library
  lifecycle: production
  owner: dep-client-platform
  system: sendbird-chat